apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../va/hci/
  # - https://github.com/openstack-k8s-operators/architecture/va/hci?ref=main
  ## It's possible to replace ../../../va/hci/ with a git checkout URL as per:
  ## https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md

# Add StorageMgmt network template, as it is needed for CephHCI
patches:
- target:
    version: v1beta1
    kind: NetConfig
    name: netconfig
  patch: |-
    - op: add
      path: /spec/networks/-
      value:
        dnsDomain: _replaced_
        name: StorageMgmt
        subnets:
          - _replaced_
        mtu: 1500

resources:
  - values.yaml

# Add StorageMgmt network replacements
replacements:
# NetConfig dnsDomain specific to this VA
- source:
    kind: ConfigMap
    name: network-values
    fieldPath: data.storagemgmt.dnsDomain
  targets:
  - select:
      kind: NetConfig
    fieldPaths:
    - spec.networks.[name=StorageMgmt].dnsDomain
# NetConfig MTU specific to this VA
- source:
    kind: ConfigMap
    name: network-values
    fieldPath: data.storagemgmt.mtu
  targets:
  - select:
      kind: NetConfig
    fieldPaths:
    - spec.networks.[name=StorageMgmt].mtu
# NetConfig subnets specific to this VA
- source:
    kind: ConfigMap
    name: network-values
    fieldPath: data.storagemgmt.subnets
  targets:
  - select:
      kind: NetConfig
    fieldPaths:
    - spec.networks.[name=StorageMgmt].subnets
