#
# CHANGEME:
#
# - Change cpu-pinning-nova ConfigMap's "data['25-cpu-pinning-nova.conf']" to use CPU sets
#   proper for your environment
# - Change sriov-nova ConfigMap's "data['03-sriov-nova.conf']" "devname" and "physical_network"
#   parameters to the proper SRIOV interface and network for your environment
#

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cpu-pinning-nova
data:
  25-cpu-pinning-nova.conf: |
    [compute]
    cpu_shared_set = 0-3,24-27 # CHANGEME
    cpu_dedicated_set = 8-23,32-47 # CHANGEME
    reserved_host_memory_mb = 4096
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sriov-nova
data:
  03-sriov-nova.conf: |
    [pci]
    passthrough_whitelist = { "devname":"eno4", "physical_network":"sriov-phy4", "trusted":"true" } # CHANGEME
---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: nova-custom-sriov
spec:
  label: dataplane-deployment-nova-custom-sriov
  configMaps:
    - cpu-pinning-nova
    - sriov-nova
  secrets:
    - nova-cell1-compute-config
    - nova-migration-ssh-key
  playbook: osp.edpm.nova
